CREATE TABLE IF NOT EXISTS "film" (
  "film_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" varchar,
  "release_date" date NOT NULL,
  "duration" integer NOT NULL,
  "mpa_rating_id" integer
);
DELETE FROM "film" CASCADE;
ALTER TABLE "film" ALTER COLUMN "film_id" RESTART WITH 1;

CREATE TABLE IF NOT EXISTS "user" (
  "user_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar NOT NULL,
  "login" varchar NOT NULL,
  "name" varchar,
  "birthday" date NOT NULL
);
DELETE FROM "user" CASCADE;
ALTER TABLE "user" ALTER COLUMN "user_id" RESTART WITH 1;

CREATE TABLE IF NOT EXISTS "mpa_rating" (
  "mpa_rating_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);
DELETE FROM "mpa_rating";
ALTER TABLE "mpa_rating" ALTER COLUMN "mpa_rating_id" RESTART WITH 1;

CREATE TABLE IF NOT EXISTS "genre" (
  "genre_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);
DELETE FROM "genre";
ALTER TABLE "genre" ALTER COLUMN "genre_id" RESTART WITH 1;

CREATE TABLE IF NOT EXISTS "film_genre" (
  "film_genre_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "film_id" integer,
  "genre_id" integer
);

DELETE FROM "film_genre";
ALTER TABLE "film_genre" ALTER COLUMN "film_genre_id" RESTART WITH 1;

CREATE TABLE IF NOT EXISTS "film_user_like" (
  "film_user_like_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "film_id" integer
);
DELETE FROM "film_user_like";
ALTER TABLE "film_user_like" ALTER COLUMN "film_user_like_id" RESTART WITH 1;

CREATE TABLE IF NOT EXISTS "user_friend" (
  "user_friend_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id_1" integer,
  "user_id_2" integer,
  "status" boolean NOT NULL DEFAULT false
);
DELETE FROM "user_friend";
ALTER TABLE "user_friend" ALTER COLUMN "user_friend_id" RESTART WITH 1;

ALTER TABLE "film" ADD FOREIGN KEY ("mpa_rating_id") REFERENCES "mpa_rating" ("mpa_rating_id");

ALTER TABLE "film_genre" ADD FOREIGN KEY ("genre_id") REFERENCES "genre" ("genre_id");

ALTER TABLE "film_genre" ADD FOREIGN KEY ("film_id") REFERENCES "film" ("film_id") ON DELETE CASCADE;;

ALTER TABLE "film_user_like" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("user_id") ON DELETE CASCADE;;

ALTER TABLE "film_user_like" ADD FOREIGN KEY ("film_id") REFERENCES "film" ("film_id") ON DELETE CASCADE;;

ALTER TABLE "user_friend" ADD FOREIGN KEY ("user_id_1") REFERENCES "user" ("user_id") ON DELETE CASCADE;;

ALTER TABLE "user_friend" ADD FOREIGN KEY ("user_id_2") REFERENCES "user" ("user_id") ON DELETE CASCADE;;
